export * from './dashboard/dashboard';
export * from './preferences/preferences';
export * from './auth/login/login';
export * from './auth/forgot/forgot';
export * from './auth/signup/signup';
export * from './auth/address/address';
export * from './auth/personal-info/personal-info';
export * from './auth/health-info/health-info';
export * from './auth/demographic/demographic';
export * from './user-profile/user-profile';
export * from './welcome-to-synerome/welcome-to-synerome';
export * from './dnadata/dnadata';
export * from './welcome/welcome';
export * from './home/home';
export * from './callControlBox/callControlBox';
export * from './confrence/confrence';
export * from './appointments/appointments';
export * from './user-list/user-list';
export * from './product-list/product-list';
export * from './product-details/product-details'

